#!/bin/bash
echo "+++++++++++++++++++++++++++++++++++++++++++++++"
echo "+   LES COMMANDES DISPONIBLES                 +"
echo "+     DELETE                                  +"
echo "+       Parametres : ALL,TABLE,LIGNE          +"
echo "+        ALL:supprime la BDD                  +"
echo "+        TABLE:supprime la table              +"
echo "+        LIGNE:supprime la ligne qui commence +"
echo "+     UPDATE                                  +"
echo "+       Parametres : ALL                      +"
echo "+        ALL:change le mot en un autre        +"
echo "+     INSERT                                  +"
echo "+       Parametres : LINE,COL                 +"
echo "+        LIGNE: inserer une ligne             +"
echo "+        COL: ajouter une nv colonne          +"
echo "+     SELECT                                  +"
echo "+       Parametres : *,TABLE                  +"
echo "+        *:tous les tables de BD              +"
echo "+        TABLE:contenu d'un tables            +"
echo "+     HELP                                    +"
echo "+       affiche ce code                       +"
echo "+     END                                     +"
echo "+       Retour au Menu principal              +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++"
read -p "Appuyer sur une touche pour continuer ..."
